### ISSUE TITLE
Links from readme_ukr.txt arent workin anymore

### ISSUE THREAD

**Issue by MoonlightRay** [jarni-ua/OP2_UKR#152]
[readme_ukr.txt](https://github.com/jarni-ua/OP2_UKR/blob/22e3769a83d78fb2b4ea90ee08ddba8a43894e6e/readme_ukr.txt#L7-L10) seems like that sounds are obsolete? Do U have them somewhere in repo?

**Comment by jarni-ua** [comment]
Thank you for pointing that out. I've updated the links.
